# Generated by Django 5.0.1 on 2024-01-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_jobs_delete_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='job_type',
            field=models.CharField(choices=[('Full TTime', 'Full Time'), ('Part TTime', 'Part Time')], default=None, max_length=15),
        ),
    ]
