# Generated by Django 5.0.1 on 2024-01-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_alter_jobs_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='salary',
            field=models.IntegerField(),
        ),
    ]
