# Generated by Django 5.0.1 on 2024-01-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_rename_category_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='job_type',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time')], max_length=15),
        ),
    ]
