# Generated by Django 5.0.1 on 2024-01-27 14:55

import job.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_jobs_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='jobs',
            options={'verbose_name_plural': 'Jobs'},
        ),
        migrations.AlterField(
            model_name='jobs',
            name='image',
            field=models.ImageField(upload_to=job.models.upload_image),
        ),
    ]
