# Generated by Django 5.0.1 on 2024-01-27 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_jobs_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
