# Generated by Django 5.0.1 on 2024-01-27 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0015_alter_jobs_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='job_type',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('2 Hour', '2 Hour')], max_length=15),
        ),
    ]
