# Generated by Django 5.0.1 on 2024-01-28 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0017_alter_jobs_job_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='apply_job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('portfolio_url', models.URLField()),
                ('cv', models.FileField(upload_to='')),
                ('cover_letter', models.TextField(max_length=600)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.jobs', verbose_name='Apply_Job')),
            ],
        ),
    ]
