# Generated by Django 5.0.1 on 2024-02-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0019_alter_apply_job_options_jobs_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='location',
            field=models.CharField(default=1, help_text='Enter the location text', max_length=255),
            preserve_default=False,
        ),
    ]
