# Generated by Django 5.0.1 on 2024-02-02 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0021_remove_jobs_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='location',
            field=models.CharField(default=1, help_text='Enter the location text', max_length=255),
            preserve_default=False,
        ),
    ]
